blueprint:
  name: "A blueprint"
  domain: "automation"
trigger:
  - d: "A trigger"
condition: >
  {% if is_state('device_tracker.paulus', 'home') %}
    Ha, Paulus is home!
  {% else %}
    Paulus is at { states('device_tracker.paulus') }}.
  {% endif %}
action:
  - some_action: {}
