blueprint:
  name: "A blueprint"
  domain: "automation"
trigger:
  - platform: event
    event_type: state_changed
condition: >
  {% if is_state('device_tracker.paulus', 'home') %}
    Ha, Paulus is home!
  {% else %}
    Paulus is at { states('device_tracker.paulus') }}.
  {% endif %}
action:
  - some_action: {}
